In [101]:
import numpy as np


In [172]:
## 怎么生成一个numpy array

## 1. one dimensional array
data1 = [1,2,3,4,5]
arr1= np.array(data1, dtype=np.float64)

##2. two dimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

##3. 特殊array 产生一个都是0的一维array .注意是zeros，不是zero
arr3 = np.zeros(5)

##4. 特殊array，产生一个都是0的二维array, 注意，里面也是括号
arr4= np.zeros((3,6))

##5. arange 产生一个一维array   (start,stop,step) 注意可以是float。np.arange(5.4)

arr5 = np.arange (0.5,10,2)

##6. arange 产生一维array，但是可以用reshape 变成二维的

arr6 = np.arange(32).reshape([8,4])

##7. random

##7.1 np.random.rand(shape) 产生shape的0-1的随机数array
arr7 = np.random.rand(5)
arr7_1 = np.random.rand(3,3)

##7.2 np.random.randint(low, high=None, (size=None), dtype=int)
arr7_2=np.random.randint (0,10,(3,3))
arr7_2_2 = np.random.randint(0,10,(5,))

##7.3 np.random.randn(shape)  产生这个shape的，符合标准正态分布的array

arr7_3= np.random.randn(3,2)


##8 
arr1d=np.array([1,2,3,4])
arr2d = arr1d[:, np.newaxis]  ## "np.newaxis" is a NumPy constant, which adds a new dimension to "arr1d"

## Hence, "arr2d" has the same elements as "arr1d", but is a two-dimensional array (a column):



In [173]:
arr2d

array([[1],
       [2],
       [3],
       [4]])

In [50]:
## numpy attributes

##1. .ndim     返回是几维的array
arr1.ndim
arr2.ndim

##2. .shape    返回array的shape， 就是the size of array along each dimension. 
print(arr1.shape)       ## 注意（5，）
print(arr2.shape)

##3。 .dtype   返回array里面的data type. 注意跟type（）的区别。

arr1.dtype 

(5,)
(2, 4)


dtype('float64')

In [51]:
## methods 

##1. np.astype() 改变data type. 注意 不改变原有的arr里的type，也就是说arr1 里的data type 还是float。
## 注意，如果float 变 int，直接砍小数点后的，不是四舍五入。四舍五入是np.around

arr1_1 = arr1.astype(np.int32)

##2. np.around([], decimal= )   list和array都可以，
l=[0.37,1.64]
a=np.array(l)
np.around(a, decimals=1)

##3. 


array([0.4, 1.6])

In [100]:
## indexing and slicing

##1. 一维跟list一样
print("##1.","\n",arr1)
print(arr1[2])
print(arr1[2:4],"\n")


##2. 二维: 先 row 再column
##2.1 取单个元素
print("##2.1","\n",arr2)
print(arr2[1,3])
print(arr2[1][3],"\n")   ## 这俩返回的一样

## 2.2 取一行和多行

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("##2.2", "\n",arr2d)
print(arr2d[:2])
print(arr2d[2],"\n")


##2.3 取一列或多列
print ("##2.3","\n",arr2d)
print(arr2d[:,2])
print(arr2d[:,:2],"\n")

## 2.4 Fetching a subset of rows and columns

print ("##2.4","\n",arr2d)
print (arr2d[:2, 1:])
print (arr2d[:2][1:])  ##这俩是不一样的。因为先【：2】返回一个两行的array，【1:】是第一行往后。

## 2.5 Fetching the first two elements of the third column: 
## :的运用。row和column的都得用，才能返回跟array一样的维度的结果。
## 举例如下：

print ("## 2.5")
print(arr2d, "\n")

print(arr2d[:2, 2], "\n")

print(arr2d[:2, 2].ndim)
print(arr2d[:2, 2].shape)

print(arr2d, "\n")

print(arr2d[:2, 2:], "\n")

print(arr2d[:2, 2:].ndim)
print(arr2d[:2, 2:].shape)

## 2.6 fancy indexing

print ("##2.6", "\n","-----")

print (arr6,"\n")

##2.6.1 同时选多个不同行 不同列的elements

print (arr6[[0,1,2,3],[0,1,2,3]],"\n")

# 2.6.2 同时选不连续的多行
print (arr6[[1,3,5]],"\n")

## 2.6.3 同时选不连续的多列
print (arr6[:,[0,2]])

####### 注意不能写 arr6[:,[:2]]  会报错
## 要写成
arr6[:,:2]   ## 连续的多列多行，就不用再加一次中括号了。


##1. 
 [1. 2. 3. 4. 5.]
3.0
[3. 4.] 

##2.1 
 [[1 2 3 4]
 [5 6 7 8]]
8
8 

##2.2 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[7 8 9] 

##2.3 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]
[[1 2]
 [4 5]
 [7 8]] 

##2.4 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[[4 5 6]]
## 2.5
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3 6] 

1
(2,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[3]
 [6]] 

2
(2, 1)
##2.6 
 -----
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[ 0  5 10 15] 

[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]] 

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]]


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21],
       [24, 25],
       [28, 29]])

In [62]:
print(arr2)


[[1 2 3 4]
 [5 6 7 8]]


In [82]:
## 赋值

##1.  array是mutable的。注意copy的问题。改变都变  举例如下：

arr1_s=arr1 [:] 

arr1_s[1]=88   # 给arr1_s的元素reassign value的时候，arr1 也变了

arr1

arr1_ss=np.copy(arr1[1:3])   ## 用copy来避免

##2. 二维array的reassign
print ("##2")
print (arr2,"\n")

arr2[1:,2:3]=100   ## 给第二行第三列的元素从新赋值
print (arr2)

##2
[[1 2 3 4]
 [5 6 7 8]] 

[[  1   2   3   4]
 [  5   6 100   8]]


array([88., 88.])

In [171]:
## boolean 

##1. 
arrb= np.array([[1,2],[3,4],[5,6]])
print (arrb)
print (arrb.ndim)
print (arrb.shape,"\n")

print (arrb>2,"/n")     ## 返回bool 跟原array同shape

print(arrb[arrb>2])   ## 返回一个一维的array, 包含原array中所有大于2的elements


##2. 
print ("##2","\n")
arr1_1=np.array([6,7,8,9,10])     ## 同维度的，必须同shape的才能比
print (arr1>arr1_1)       ## 返回一个同shape bool array


##3. np.sum()计算true value的个数
arr__3 = np.random.randn(5, 2)

print(arr__3, "\n")

print(np.sum(arr__3 > 0, axis = 0))  ## The sum of all True values for each column
print(np.sum(arr__3 > 0, axis = 1))  ## The sum of all True values for each row



##4. np.any()  & np.all()  看是否有true value 或者全部都是true 

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2) 

[[False False]
 [ True  True]
 [ True  True]] /n
[3 4 5 6]
##2 

[False False False False False]
[[ 0.19932446 -1.24120445]
 [-0.46316933  0.71177215]
 [ 0.05704241  0.8213982 ]
 [ 0.64518909  0.53022558]
 [ 0.54760604  0.05737485]] 

[4 4]
[1 1 2 2 2]


In [117]:
## Arithmetics 

##1. 同维度的,same shape的 array 直接 + - * /
print ("##1","\n")
print (arr1,"\n")
print (arr2,"\n")
print (arr1+arr1,"\n")
print (arr2*arr2,"\n")

##2. 同纬度，不同shape的  不可以，会报错。
print ("##2","\n")
arr2_1=np.array([[1,2,3],[4,5,6]])
print (arr2_1,"\n")
## print (arr2+arr2_1)

##3. broadcasting

print ("##3","\n")
arr2d = np.array([[0],
                   [10],
                   [20],
                   [30]])

arr1d = np.array([0, 1, 2])

print(arr2d, "\n")

print(arr1d, "\n")

print(arr2d + arr1d)       ### 跟

##3.1 Arithmetic operations on a scalar and an array

print ("##3.1","\n")
print (arr2d)
print (arr2d+10)   ## 10会broadcast成跟原array一样的shape的array。
## 注意 list就不能与scalar 作+-/，唯独*可以



##1 

[1. 2. 3. 4. 5.] 

[[1 2 3 4]
 [5 6 7 8]] 

[ 2.  4.  6.  8. 10.] 

[[ 1  4  9 16]
 [25 36 49 64]] 

##2 

[[1 2 3]
 [4 5 6]] 

##3 

[[ 0]
 [10]
 [20]
 [30]] 

[0 1 2] 

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
##3.1 

[[ 0]
 [10]
 [20]
 [30]]
[[10]
 [20]
 [30]
 [40]]


In [169]:
## Universal Functions:

## 注意，都是element wise

##1. np.sqrt(),&  np.exp()  &&  np.abs()

arr = np.arange(10)

print(arr, "\n")

print(np.sqrt(arr),"\n")

print (np.exp(arr),"\n")


##2. np.where (condintion,x,y) 跟excel里的if函数很像
print("##2","\n")

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond=np.array([True, False, True, True, False])

print (xarr,"\n")
print (yarr,"\n")

print (np.where(1>2,xarr,yarr))  # condition true 从x选，condition false 从y选
print (np.where(cond,yarr,xarr))

print ("\n")

arr_randn=np.random.randn(3,3)

print (arr_randn)
print (np.where(arr_randn>0,"+","-"))


##3. np.maximum() & np.minimum()
## Compare two arrays and return a new array containing the element-wise maxima and minima, respectively.

x=np.random.rand(8)
y=np.random.rand(8)
np.maximum(x,y)

##4. np.amax() & np.amin()
## np.amax() returns the maximum of an array or maximum along an axis.
## np.amin() returns the minimum of an array or minimum along an axis.
print ("##4","\n")
arr_4 = np.arange(10).reshape((5,2))
print (arr_4)
##4.1 
print ("##4.1","\n")
print (np.amax(arr_4))
print (np.amin(arr_4))
##4.2 
print ("##4.2","\n")
print (np.amax(arr_4,axis=0))   ## axis=0 就是按row方向 collapse
print (np.amin(arr_4,axis=0),"\n")

print (np.amax(arr_4,axis=1))    ## 按column方向 collapse ，但是返回的是一个一维的array，不是按列返回的。
print (np.amin(arr_4,axis=1))


##5. np.mean()

print ("##5", "\n")
arr_5=np.arange(9).reshape(3,3)
print (arr_5)

print (np.mean(arr_5))
print (np.mean(arr_5,axis=0))  
print (np.mean(arr_5,axis=1))

## 6. np.sum()

print ("##6", "\n")
arr_5=np.arange(9).reshape(3,3)
print (arr_5)

print (np.sum(arr_5))
print (np.sum(arr_5,axis=0))  
print (np.sum(arr_5,axis=1))

##7.  np.sort() 也可以分axis=0 和 axis=1, 但不改变原来的arr

##8. np.unique()  Find the unique elements of an array.


[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 

##2 

[1.1 1.2 1.3 1.4 1.5] 

[2.1 2.2 2.3 2.4 2.5] 

[2.1 2.2 2.3 2.4 2.5]
[2.1 1.2 2.3 2.4 1.5]


[[ 1.57029416  1.23464621  0.0532535 ]
 [ 0.48675128 -0.44927045 -1.23742642]
 [ 1.72952308 -0.03918784  0.48387516]]
[['+' '+' '+']
 ['+' '-' '-']
 ['+' '-' '+']]
##4 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
##4.1 

9
0
##4.2 

[8 9]
[0 1] 

[1 3 5 7 9]
[0 2 4 6 8]
##5 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0
[3. 4. 5.]
[1. 4. 7.]
##6 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
[ 9 12 15]
[ 3 12 21]


In [174]:
a=np.array([3,4,6,10,24,89,45,43,46,99,100])

In [175]:
print (a)

[  3   4   6  10  24  89  45  43  46  99 100]


In [177]:
a[a%3 !=0]

array([  4,  10,  89,  43,  46, 100])